/**
 * export-music-midi.mts — MIDI stem export (the Ableton pipeline).
 *
 *   npx tsx scripts/export-music-midi.mts [bars]
 *
 * Writes, for every (region x intensity) in the state matrix:
 *   scripts/shots/music-midi/<region>-<intensity>-<layer>.mid   one stem each
 *   scripts/shots/music-midi/<region>-<intensity>-ALL.mid       all layers
 *   scripts/shots/music-midi/README.md                          the mapping
 *
 * These are exactly the notes the synth plays — same arranger, same seed — so
 * a layer rendered through an Ableton instrument can replace its synth
 * counterpart without the arrangement moving. See src/game/music/layer.ts for
 * the seam that swap would go through.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  INTENSITIES,
  LAYERS,
  REGIONS,
  REGION_CONFIG,
  arrangeSequence,
  layerStream,
  type Intensity,
  type MusicState,
  type Region,
} from '../src/game/music/index';
import { buildStem, keySignature, notesToMidi, writeSmfMulti } from '../src/game/music/midi';
import { MODES, midiToPitchClass, romanNumeral } from '../src/game/music/theory';
import { DRUM_MIDI } from '../src/game/music/arranger';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'shots', 'music-midi');
const SEED = 20260727;
const BARS = Number(process.argv[2] ?? 16);

mkdirSync(OUT, { recursive: true });

interface Row {
  region: Region;
  intensity: Intensity;
  bpm: number;
  mode: string;
  key: string;
  sf: number;
  counts: Record<string, number>;
}
const rows: Row[] = [];
let files = 0;

for (const region of REGIONS) {
  for (const intensity of INTENSITIES) {
    const st: MusicState = { region, intensity, tod: 0.4, weather: 0, paused: false };
    const seq = arrangeSequence(SEED, st, BARS);
    const plan = seq[0]!.plan;
    const counts: Record<string, number> = {};

    for (const layer of LAYERS) {
      const stream = layerStream(seq, layer);
      counts[layer] = stream.length;
      const name = `${region}-${intensity}-${layer}`;
      writeFileSync(join(OUT, `${name}.mid`), buildStem(name, stream, plan, layer === 'perc'));
      files++;
    }

    const all = writeSmfMulti({
      bpm: plan.bpm,
      name: `${region}-${intensity}`,
      mode: plan.mode,
      tonicPc: ((plan.tonicMidi % 12) + 12) % 12,
      tracks: LAYERS.map((l) => ({
        name: l,
        notes: notesToMidi(layerStream(seq, l)),
        channel: l === 'perc' ? 9 : 0,
      })),
    });
    writeFileSync(join(OUT, `${region}-${intensity}-ALL.mid`), all);
    files++;

    const [sf] = keySignature(((plan.tonicMidi % 12) + 12) % 12, plan.mode);
    rows.push({
      region,
      intensity,
      bpm: Math.round(plan.bpm * 100) / 100,
      mode: plan.mode,
      key: `${midiToPitchClass(plan.tonicMidi)} ${plan.mode}`,
      sf,
      counts,
    });
  }
}

// --------------------------------------------------------------------- README

const accidental = (sf: number) =>
  sf === 0 ? 'none' : sf > 0 ? `${sf} sharp${sf > 1 ? 's' : ''}` : `${-sf} flat${-sf > 1 ? 's' : ''}`;

const md: string[] = [];
md.push('# A Tale of Yarn — MIDI stems');
md.push('');
md.push(
  `Generated by \`scripts/export-music-midi.mts\` from seed \`${SEED}\`, ${BARS} bars per file.`,
);
md.push(
  'These are the exact note events the in-game synth plays. Re-running the script with the',
  'same seed reproduces byte-identical files — the export is deterministic and is asserted',
  'as such in `scripts/test-music.mts`.',
);
md.push('');
md.push('## Files');
md.push('');
md.push('```');
md.push('<region>-<intensity>-<layer>.mid   one layer, format 1 (conductor + notes)');
md.push('<region>-<intensity>-ALL.mid       every layer as separate tracks, format 1');
md.push('```');
md.push('');
md.push(`Regions: ${REGIONS.join(', ')}  ·  Intensities: ${INTENSITIES.join(', ')}`);
md.push(`Layers: ${LAYERS.join(', ')}`);
md.push('');
md.push('## Musical setup');
md.push('');
md.push(
  'Everything is in **D**, 4/4, on a 16th-note grid (480 PPQ, 120 ticks per 16th).',
  'A region change is a MODE change, never a key change — that is what lets the layers',
  'crossfade into each other without a modulation. Tempo is the region tempo multiplied',
  'by an intensity factor (calm/alert 1.00, combat 1.12, boss 1.18).',
);
md.push('');
md.push('| region | intensity | BPM | key/mode | key sig | progression |');
md.push('|---|---|---|---|---|---|');
for (const r of rows) {
  const cfg = REGION_CONFIG[r.region];
  const prog = cfg.progression.map((d) => romanNumeral(d, cfg.mode)).join(' – ');
  md.push(
    `| ${r.region} | ${r.intensity} | ${r.bpm} | ${r.key} | ${accidental(r.sf)} | ${prog} |`,
  );
}
md.push('');
md.push('## The motif');
md.push('');
md.push(
  'One theme, 4 bars, 13 notes, stated in scale degrees so it survives every mode:',
);
md.push('');
md.push('```');
md.push('degrees   0  4  3  4 | 2  1  0.. | 0  4  5  6 | 7....  4....');
md.push('in D ion. D  A  G  A | F# E  D   | D  A  B  C#| D(oct) A');
md.push('in D aeo. D  A  G  A | F  E  D   | D  A  Bb C | D(oct) A');
md.push('in D phr. D  A  G  A | F  Eb D   | D  A  Bb C | D(oct) A   <- the King');
md.push('```');
md.push('');
md.push(
  'Degree intervals `[+4,-1,+1,-2,-1,-1,0,+4,+1,+1,+1,-3]`. The first four,',
  '`[+4,-1,+1,-2]`, are the fingerprint the test suite searches for. Note that aeolian',
  'and phrygian differ on exactly ONE note of the theme — the `1` in bar 2 — so the',
  'castle music is the village tune with a single semitone moved.',
);
md.push('');
md.push('## Layer -> instrument mapping');
md.push('');
md.push('| layer | channel | role | suggested Ableton instrument |');
md.push('|---|---|---|---|');
md.push('| pad | 1 | sustained harmony bed, 2 voices | warm analog pad, slow attack (~0.85 s) |');
md.push('| bass | 1 | root motion; driving eighths at combat | soft sine/triangle bass, short decay |');
md.push('| melody | 1 | THE MOTIF | music box / celesta / plucked dulcimer |');
md.push('| pluck | 1 | arpeggio, the "knitting needles" texture | nylon guitar / kalimba / harp |');
md.push('| perc | **10** | frame drum kit | see GM map below |');
md.push('| tension | 1 | hollow fifth drone with 5.5 Hz tremolo | bowed low string / dark drone |');
md.push('');
md.push('Percussion uses GM drum numbers on channel 10:');
md.push('');
for (const [k, v] of Object.entries(DRUM_MIDI)) md.push(`- \`${v}\` — ${k}`);
md.push('');
md.push('## If you render these to audio');
md.push('');
md.push(
  'A rendered loop can replace a synth layer at runtime. Two constraints, from',
  '`src/game/music/layer.ts`:',
);
md.push('');
md.push('1. Render at the exact BPM in the table above, in D, in that mode.');
md.push('2. Make it a whole number of bars (4 or 8) so it stays phase-locked to the bar grid.');
md.push('');
md.push('Tails may overhang the loop point — the engine never cuts a note.');
md.push('');
md.push('## Note counts');
md.push('');
md.push(`| region | intensity | ${LAYERS.join(' | ')} |`);
md.push(`|---|---|${LAYERS.map(() => '---').join('|')}|`);
for (const r of rows) {
  md.push(`| ${r.region} | ${r.intensity} | ${LAYERS.map((l) => r.counts[l]).join(' | ')} |`);
}
md.push('');

writeFileSync(join(OUT, 'README.md'), md.join('\n'), 'utf8');

process.stdout.write(
  `music-midi: ${files} .mid files + README.md -> ${OUT}\n` +
    `  ${REGIONS.length} regions x ${INTENSITIES.length} intensities x ${LAYERS.length} layers, ${BARS} bars each\n`,
);
